server:
  port: 8090

spring:
  application:
    name: resource-server

  datasource:
    url: jdbc:mariadb://localhost:3306/cdo
    username: vd
    password: 111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks